PROG = mpk.dll
DEF_FILE = ../Archive.def
OBJ_EXT = obj

AR_OBJS = \
  $O/ArchiveExports.$(OBJ_EXT) \
  $O/DllExports.$(OBJ_EXT) \

!include "./makefile_objects"

!include "../../Crc.mak"

!include "../../7zip.mak"
