name: Build GGPK dll

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_win32:
    name: ggpk.dll Windows Build
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: build amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - run: |
          cd CPP/7zip/Archive/Ggpk
          nmake
      - name: build x86
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86
      - run: |
          cd CPP/7zip/Archive/Ggpk
          nmake
      - name: build arm64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_arm64
      - run: |
          cd CPP/7zip/Archive/Ggpk
          nmake
      - name: Upload DLLs
        uses: actions/upload-artifact@v4
        with: 
          name: DLLs
          path: |
            CPP/7zip/Archive/Ggpk/x64/ggpk.dll
            CPP/7zip/Archive/Ggpk/x86/ggpk.dll
            CPP/7zip/Archive/Ggpk/arm64/ggpk.dll
